### ISSUE TITLE
npm package missing images

### ISSUE THREAD

**Issue by RinkAttendant6** [harvesthq/chosen#2641]
Related to: #1433, #2631 

The npm package appears to be missing two images that are referenced by the CSS:

![Console error: HTTP/1.1 404 Not Found chosen-sprite.png](https://cloud.githubusercontent.com/assets/351158/16543813/33f6f4d6-40b9-11e6-88bc-dbf6b85e8e69.png)

### Steps to reproduce
1. Install: `npm install chosen-js --save`
2. Load the JS file using `<script>`, `require('chosen-js')` or `import 'chosen-js'`
3. Load the CSS file using `@import` or `<link>`
4. Instantiate Chosen on a select element and open the page

### Expected behavior

No missing resources

### Actual behavior

HTTP 404 for the images `chosen-sprite.png` and `chosen-sprite@2x.png`

### Environment

  - **Chosen Version**: 1.6.1
  - **jQuery or Prototype Version**: 2.2.4, but irrelevant
  - **Browser and Version**: Chrome and Firefox, but irrelevant
  - **OS and Version**: Linux Mint and Windows 10, but irrelevant

### Additional information

I've never published anything to npm before but I assume the two files need to be added to the files array in `package.json`?

**Comment by firestar300** [comment]
Same problem here.

**Comment by tjschuck** [comment]
Fixed by #2643

**Comment by chrisber** [comment]
Please update the npm package, thanks

**Comment by Skeldave** [comment]
I'm still not seeing the images when installing the chosen-js npmpackage.

Thanks.

**Comment by koenpunt** [comment]
I've tagged a new release just now, although for some reason the package isn't being published automatically... will check this in the morning.

**Comment by koenpunt** [comment]
Turned out I forgot to up the version in `package.json`, 1.6.2 is on npm now
